import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar"
import Hero from "../components/Hero"
import Link from '../components/Link'
import Links from '../components/Links'
import Boost from '../components/Boost'
import Footer from "../components/Footer"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TIF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;800&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Navbar />
     <Hero />
     <Link />
     <Links />
     <Boost />
     <Footer />
    </div>
  )
}
